services:
  db:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydba
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data


  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  my-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: ["sh", "-c", "npx prisma generate && npx prisma db push --force-reset && npm run dev -- -p 8080"]
    depends_on:
      - db
      - redis
    deploy:
      resources:
        limits:
          memory: 1g  # or higher, e.g., 2g or 4g depending on your server


volumes:
  postgres-data:
