services:
  db:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydba
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  my-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: ["sh", "-c", "npx prisma generate && npx prisma db push --force-reset && npm run dev -- -p 8080"]
    depends_on:
      - db

volumes:
  postgres-data:
